-- Supabase keep-alive 表
-- 在每個要保活的 Supabase 專案的 SQL Editor 各跑一次（ULLD 一次、asset-mgmt 一次）。
-- 之後由 .github/workflows/keepalive.yml 每天 insert 一筆來維持活動。

CREATE TABLE IF NOT EXISTS keep_alive (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pinged_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
